<?xml version="1.0" encoding="utf-8"?><Database Name="CinemaManagement" Class="ConnectDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=CinemaManagement;Integrated Security=True;Encrypt=True;Trust Server Certificate=True" SettingsObjectName="Cinema_Management_System.Properties.Settings" SettingsPropertyName="CinemaManagementConnectionString2" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ACCOUNTS" Member="ACCOUNTs">
    <Type Name="ACCOUNT">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="Staff_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="STAFF_ACCOUNT" Member="STAFF" ThisKey="Staff_Id" OtherKey="Id" Type="STAFF" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Auditorium" Member="Auditoriums">
    <Type Name="Auditorium">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NumberOfSeats" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Auditorium_Seat" Member="Seats" ThisKey="Id" OtherKey="Auditorium_Id" Type="Seat" />
      <Association Name="Auditorium_ShowTime" Member="ShowTimes" ThisKey="Id" OtherKey="Auditorium_Id" Type="ShowTime" />
    </Type>
  </Table>
  <Table Name="dbo.Bill" Member="Bills">
    <Type Name="Bill">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Staff_Id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Customer_Id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ShowTime_Id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BillDate" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="QuantityTicket" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PerSeatTicketPrice" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Discount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="Total" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Bill_SeatForShowtime" Member="SeatForShowtimes" ThisKey="Id" OtherKey="Condition" Type="SeatForShowtime" />
      <Association Name="STAFF_Bill" Member="STAFF" ThisKey="Staff_Id" OtherKey="Id" Type="STAFF" IsForeignKey="true" />
      <Association Name="ShowTime_Bill" Member="ShowTime" ThisKey="ShowTime_Id" OtherKey="Id" Type="ShowTime" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Bill_AddProduct" Member="Bill_AddProducts">
    <Type Name="Bill_AddProduct">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Product_Id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BillDate" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UnitPurchasePrice" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Total" Type="System.Int32" DbType="Int" IsDbGenerated="true" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Product_Bill_AddProduct" Member="Product" ThisKey="Product_Id" OtherKey="ID" Type="Product" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Bill_ImportProduct" Member="Bill_ImportProducts">
    <Type Name="Bill_ImportProduct">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Product_Id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BillDate" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UnitPurchasePrice" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Total" Type="System.Int32" DbType="Int" IsDbGenerated="true" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Product_Bill_ImportProduct" Member="Product" ThisKey="Product_Id" OtherKey="ID" Type="Product" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CUSTOMER" Member="CUSTOMERs">
    <Type Name="CUSTOMER">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdFormat" Type="System.String" DbType="VarChar(32)" IsDbGenerated="true" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PhoneNumber" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Point" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Birth" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="RegDate" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="Gender" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Seat" Member="Seats">
    <Type Name="Seat">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Location" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="Auditorium_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Seat_SeatForShowtime" Member="SeatForShowtimes" ThisKey="Id" OtherKey="Seat_Id" Type="SeatForShowtime" />
      <Association Name="Auditorium_Seat" Member="Auditorium" ThisKey="Auditorium_Id" OtherKey="Id" Type="Auditorium" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.STAFF" Member="STAFFs">
    <Type Name="STAFF">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Birth" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="Gender" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="PhoneNumber" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Salary" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Role" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="NgayVaoLam" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="ImageSource" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="STAFF_ACCOUNT" Member="ACCOUNTs" ThisKey="Id" OtherKey="Staff_Id" Type="ACCOUNT" />
      <Association Name="STAFF_Bill" Member="Bills" ThisKey="Id" OtherKey="Staff_Id" Type="Bill" />
      <Association Name="STAFF_Staff_Salary" Member="Staff_Salaries" ThisKey="Id" OtherKey="Staff_Id" Type="Staff_Salary" />
      <Association Name="STAFF_Bill_SellProduct" Member="Bill_SellProducts" ThisKey="Id" OtherKey="Staff_Id" Type="Bill_SellProduct" />
    </Type>
  </Table>
  <Table Name="dbo.Staff_Salary" Member="Staff_Salaries">
    <Type Name="Staff_Salary">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Staff_Id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BillDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Total" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="STAFF_Staff_Salary" Member="STAFF" ThisKey="Staff_Id" OtherKey="Id" Type="STAFF" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MOVIE" Member="MOVIEs">
    <Type Name="MOVIE">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MovieCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Genre" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Director" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ReleaseYear" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Language" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Length" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Trailer" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="StartDate" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="EndDate" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ImportPrice" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ImageSource" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="TotalShowtimes" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CurrentShowtimes" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="MOVIE_Bill_AddMovie" Member="Bill_AddMovies" ThisKey="id" OtherKey="Movie_Id" Type="Bill_AddMovie" />
      <Association Name="MOVIE_ShowTime" Member="ShowTimes" ThisKey="id" OtherKey="Movie_Id" Type="ShowTime" />
    </Type>
  </Table>
  <Table Name="dbo.Bill_AddMovie" Member="Bill_AddMovies">
    <Type Name="Bill_AddMovie">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Movie_Id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BillDate" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="Total" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="MOVIE_Bill_AddMovie" Member="MOVIE" ThisKey="Movie_Id" OtherKey="id" Type="MOVIE" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ShowTime" Member="ShowTimes">
    <Type Name="ShowTime">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StartTime" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="EndTime" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="PerSeatTicketPrice" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Movie_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Auditorium_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="ShowTime_Bill" Member="Bills" ThisKey="Id" OtherKey="ShowTime_Id" Type="Bill" />
      <Association Name="Auditorium_ShowTime" Member="Auditorium" ThisKey="Auditorium_Id" OtherKey="Id" Type="Auditorium" IsForeignKey="true" />
      <Association Name="MOVIE_ShowTime" Member="MOVIE" ThisKey="Movie_Id" OtherKey="id" Type="MOVIE" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SeatForShowtime" Member="SeatForShowtimes">
    <Type Name="SeatForShowtime">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Seat_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ShowTime_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Condition" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Bill_SeatForShowtime" Member="Bill" ThisKey="Condition" OtherKey="Id" Type="Bill" IsForeignKey="true" />
      <Association Name="Seat_SeatForShowtime" Member="Seat" ThisKey="Seat_Id" OtherKey="Id" Type="Seat" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Bill_SellProduct" Member="Bill_SellProducts">
    <Type Name="Bill_SellProduct">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BillDate" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="Staff_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StaffName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="TotalAmount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Bill_SellProduct_BillDetailProduct" Member="BillDetailProducts" ThisKey="Id" OtherKey="Bill_Id" Type="BillDetailProduct" />
      <Association Name="STAFF_Bill_SellProduct" Member="STAFF" ThisKey="Staff_Id" OtherKey="Id" Type="STAFF" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.BillDetailProduct" Member="BillDetailProducts">
    <Type Name="BillDetailProduct">
      <Column Name="Bill_Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Product_Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UnitPrice" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TotalPrice" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Bill_SellProduct_BillDetailProduct" Member="Bill_SellProduct" ThisKey="Bill_Id" OtherKey="Id" Type="Bill_SellProduct" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Product" Member="Products">
    <Type Name="Product">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ImageSource" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PurchasePrice" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Product_Bill_AddProduct" Member="Bill_AddProducts" ThisKey="ID" OtherKey="Product_Id" Type="Bill_AddProduct" />
      <Association Name="Product_Bill_ImportProduct" Member="Bill_ImportProducts" ThisKey="ID" OtherKey="Product_Id" Type="Bill_ImportProduct" />
    </Type>
  </Table>
</Database>